---
# tasks file for artifactory

# Create a User named Artifactory to execute artifactory as a user
- name: Add the user 'artifactory'
  ansible.builtin.user:
    name: artifactory
    comment: Artifactory-Service-Account
    # group: artifactory
  tags:
    - user

# Install some tools
# - name: "Install some tools when Rocky"
#   yum:
#     name: 
#       - "wget"
#       - "tar"
#       - "unzip"
#       - "nginx"
#       - "python3-libsemanage"
#       - "policycoreutils-devel.x86_64"
#       - "setroubleshoot-server.x86_64"
#       - "setools-console-4.3.0-5.el8.x86_64"
#       - "net-tools-2.0-0.52.20160912git.el8.x86_64" # Needed for Artifactory
#     state: "present"

- name: "Install some tools when RHEL"
  yum:
    name: 
      - "wget"
      - "tar"
      - "unzip"
      - "nginx"
      - "python3-libsemanage"
      - "policycoreutils-devel.x86_64"
      - "setroubleshoot-server.x86_64"
      - "setools.x86_64"
      - "net-tools-2.0-0.52.20160912git.el8.x86_64" # Needed for Artifactory
    state: "present"
  when: ansible_distribution == 'RedHat'

# Create some working directories
- name: "Create jfrog-Working Directories"
  file:
    path: "{{ item }}"
    #owner: root
    #group: root
    #mode: '0755'
    state: directory
    recurse: true
  loop:
    - "{{dir_root}}"
    - "{{dir_ssl_certs}}"

# Download Binaries
- name: Download jfrog tar.gz
  get_url:
    url: "{{jfrog_download_url}}"
    dest: "{{dir_root}}{{jfrog_filename}}"

# Unarchive Binary
- name: "Unarchive jfrog tar.gz"
  unarchive:
    src: "{{dir_root}}{{jfrog_filename}}"
    dest: "{{ dir_root }}"
    remote_src: yes

# Open some firewall ports
- name: "Firewall - Open http and https firewall-services"
  firewalld:
    service: "{{item}}"
    permanent: yes
    state: "enabled"
  with_items:
    - "http"
    - "https"

- name: "Firewall - Open some firewall-ports"
  ansible.posix.firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  loop:
    - "8081/tcp"
    - "8082/tcp"
    - "80/tcp"
    - "443/tcp"
  notify:
    - Restart Firewalld


# Copy SSL-Certificates to Nginx
- name: "Copy artifactory.config.import.xml to start Artifactory with predefined config"
  copy:
    src: "{{item}}"
    dest: "{{dir_ssl_certs}}"
  loop:
    - "wildcard-artifactory-crt.pem"
    - "wildcard-artifactory-key.pem"
    - "password-for-private-key"

# Configure Nginx
- name: "Template /etc/nginx/nginx.conf for Artifactory"
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: "Template nginx.conf for Artifactory"
  template:
    src: "templates/nginx-artifactory.conf.j2"
    dest: "/etc/nginx/conf.d/nginx-artifactory.conf"

# Accept Eula
- name: "Template eula-accept.yaml for Artifactory"
  template:
    src: "templates/eula-accept.yaml"
    dest: "{{dir_install}}/var/etc/artifactory/artifactory.config.import.yml"

# Copy artifactory.config.latest.xml for bootstrapping
# $JFROG_HOME/artifactory/var/etc/artifactory/artifactory.config.import.xml
# - name: "Copy artifactory.config.import.xml to start Artifactory with predefined config"
#   copy:
#     src: artifactory.config.import.xml
#     dest: "{{dir_root}}artifactory-jcr-{{jfrog_version}}/var/etc/artifactory/artifactory.config.import.xml"

# chown -R artifactory:artifactory /jfrog/downloads/artifactory-jcr-7.27.6/app
# Change Ownership of jfrog-App-Directory
- name: Recursively change ownership of jfrog-App-Directory
  ansible.builtin.file:
    path: "{{dir_root}}"
    state: directory
    recurse: yes
    owner: artifactory
    group: artifactory
  tags:
    - user
# Set Selinux Policies
- name: Add custom SELinux fcontext
  sefcontext:
    target: "{{ dir_ssl_certs | regex_replace('/$') }}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  when: selinux_is_enabled
  tags:
    - selinux

- name: Restorecon on jfrog-root-dir
  command: "/usr/sbin/restorecon -Rv {{ dir_ssl_certs }}" 
  when: selinux_is_enabled
  tags:
    - selinux
# Start Artifactory via systemd
# /jfrog/downloads/artifactory-jcr-7.27.6/app/bin/artifactory.sh start
- name: "Copy template-systemd-file to systemd"
  template:
    src: "templates/systemd-artifactory-service.j2"
    dest: "/usr/lib/systemd/system/artifactory.service"
  # tags:
  #   - systemd

# Systemd - daemon-reload
- name: Just force systemd to reread configs - systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - systemd

# Start Nginx via systemd
- name: Make sure a nginx-service unit is running
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: true
  tags:
    - systemd
# Start Artifactory via systemd
- name: Make sure a artifactory-service unit is running
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: artifactory.service
  tags:
    - systemd