---
# tasks file for artifactory

# Create a User named Artifactory to execute artifactory as a user
- name: Add the user 'artifactory'
  ansible.builtin.user:
    name: artifactory
    comment: Artifactory-Service-Account
    # group: artifactory
  tags:
    - user

# Install some tools
- name: "Install some tools"
  yum:
    name: 
      - "wget"
      - "tar"
      - "unzip"
      - "nginx"
      - "python3-libsemanage"
      - "policycoreutils-devel.x86_64"
      - "setroubleshoot-server.x86_64"
    state: "present"

# Create some working directories
- name: "Create jfrog-Working Directories"
  file:
    path: "{{ item }}"
    #owner: root
    #group: root
    #mode: '0755'
    state: directory
    recurse: true
  loop:
    - "{{dir_root}}"
    - "{{dir_downloads}}"
    - "{{dir_ssl_certs}}"

# Download Binaries
- name: Download jfrog Binaries
  get_url:
    url: "{{jfrog_download_url}}"
    dest: "{{dir_downloads}}{{jfrog_filename}}"

# Unarchive Binary
- name: "Unarchive jfrog binary"
  unarchive:
    src: "{{dir_downloads}}{{jfrog_filename}}"
    dest: "{{ dir_downloads }}"
    remote_src: yes

# Open some firewall ports
- name: "Open some firewall-ports"
  firewalld:
    service: "{{item}}"
    permanent: yes
    state: "enabled"
  with_items:
    - "http"
    - "https"

- name: Allow to open some Firewall-Ports
  ansible.posix.firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  loop:
    - "8081/tcp"
    - "8082/tcp"
    - "80/tcp"
    - "443/tcp"
  notify:
    - Restart Firewalld


# Copy SSL-Certificates to Nginx
- name: "Copy artifactory.config.import.xml to start Artifactory with predefined config"
  copy:
    src: "{{item}}"
    dest: "{{dir_ssl_certs}}"
  loop:
    - "wildcard-artifactory-crt.pem"
    - "wildcard-artifactory-key.pem"
    - "password-for-private-key"

# Configure Nginx
- name: "Template nginx.conf for Artifactory"
  template:
    src: "templates/nginx-artifactory.conf.j2"
    dest: "/etc/nginx/conf.d/nginx-artifactory.conf"

# Copy artifactory.config.latest.xml for bootstrapping
# $JFROG_HOME/artifactory/var/etc/artifactory/artifactory.config.import.xml
- name: "Copy artifactory.config.import.xml to start Artifactory with predefined config"
  copy:
    src: artifactory.config.import.xml
    dest: "{{dir_downloads}}artifactory-jcr-{{jfrog_version}}/var/etc/artifactory/artifactory.config.import.xml"

# chown -R artifactory:artifactory /jfrog/downloads/artifactory-jcr-7.27.6/app
# Change Ownership of jfrog-App-Directory
- name: Recursively change ownership of jfrog-App-Directory
  ansible.builtin.file:
    path: "{{dir_root}}"
    state: directory
    recurse: yes
    owner: artifactory
    group: artifactory
  tags:
    - user
# Set Selinux Policies
- name: Add custom SELinux fcontext
  sefcontext:
    target: "{{ dir_ssl_certs | regex_replace('/$') }}(/.*)?"
    setype: httpd_sys_content_t
    state: present
  tags:
    - selinux

- name: Restorecon on tftproot_path
  command: "/usr/sbin/restorecon -Rv {{ dir_ssl_certs }}" 
  tags:
    - selinux
# Start Artifactory via systemd
# /jfrog/downloads/artifactory-jcr-7.27.6/app/bin/artifactoryctl start
- name: "Copy template-systemd-file to systemd"
  template:
    src: "templates/systemd-artifactory-service.j2"
    dest: "/usr/lib/systemd/system/artifactory.service"
  # tags:
  #   - systemd

# Systemd - daemon-reload
- name: Just force systemd to reread configs - systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - systemd

# Start Nginx via systemd
- name: Make sure a nginx-service unit is running
  ansible.builtin.systemd:
    state: started
    name: nginx
  tags:
    - systemd
# Start Artifactory via systemd
- name: Make sure a artifactory-service unit is running
  ansible.builtin.systemd:
    state: started
    name: artifactory.service
  tags:
    - systemd